services:
  tavern-rikka-bridge:
    image: ghcr.io/spancerxing/tavern-rikka-bridge:latest
    container_name: tavern-rikka-bridge
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - BASE_PATH=/
    build:
      context: .
